config/routes.rb
SummerWine::Application.routes.draw do
  get "welcome/index"
  get "welcome/about"

  resources :posts do
		resources :comments
	end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root 'welcome#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
	validates :desc,  :presence => true, :length => { :minimum => 3 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :post_category
  belongs_to :user
	has_many :comments, :dependent => :destroy
	validates_presence_of :post_category_id, :title, :desc
	is_impressionable

	def self.search(keywords)
		posts = order("created at desc")
		posts = posts.where("posts.title like ? OR posts.desc like ?", "%#{keywords}%", "%#{keywords}%" ) if keywords.present?
		posts
	end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post_group
	has_many :posts
end

app/models/post_group.rb
class PostGroup < ActiveRecord::Base
	has_many :post_categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
		@comment = Comment.new(comment_params)

		respond_to do |format|
			if @comment.save
				format.html { redirect_to @comment.post, notice: '댓글이 성공적으로 작성되었습니다.' }  
				format.json { render action: 'show', status: :created, location: @comment }   
			else
				format.html { render action: 'new' }
				format.json { render json: @comment.errors, status: :unprocessable.entity } 
			end
		end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
		post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
			@comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :desc)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, except: [:index, :show]
	impressionist

  # GET /posts
  # GET /posts.json
  def index
		@offset = 20
		@page = params[:page]
		if category = PostCategory.find_by_name(params[:category])
			@posts = category.posts.order('created_at desc').page(@page).per(@offset)
			@total_count = category.posts.count
			@category = params[:category]
			@cate_id = category.name
		else
			@posts = Post.search(params[:search]).page(@page).per(@offset)
			@total_count = Post.search(params[:search]).count
			@category = 'Result'
		end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
		@page = params[:page]
  end

  # GET /posts/new
  def new
		@category = PostCategory.find_by_name(params[:category])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
		@category = PostCategory.find_by_name(params[:category])
		@page = params[:page]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
		category = params[:category]
		page = params[:page]
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url(:category => category, :page => page) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_category_id, :user_id, :title, :desc)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		default_url = "#{root_url}assets/images/ahsan/guest.jpg"
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=#{CGI.escape(default_url)}"
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(comment, :url => post_comments_path(@post)) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :post_id, :as => :hidden, :input_html => { :value => @post.id } %>

  <div class="form-inputs">
    <%= f.input :desc, :input_html => { :placeholder => "댓글 쓰세요.", :class => 'span12'}, :label => false %>
  </div>

  <div class="form-actions">
    <%= f.submit "Comment", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<table class='table'>
  <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email.split('@')[0] %></td>
        <td><%= simple_format comment.desc %></td>
				<td class="pull-right">
					<%= link_to '삭제', [comment.post, comment],
               :confirm => 'Are you sure?', :class => "btn btn-mini btn-danger",
               :method => :delete %>
				</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Post</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user %></td>
    <td><%= comment.post %></td>
    <td><%= comment.desc %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>

<p>
  <b>Desc:</b>
  <%= @comment.desc %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Summer Hill" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
					<a class="brand" href="#">
						SummerHill	
					</a>
					
					<% 
						arr = ['btn-success', 'btn-danger', 'btn-info', 'btn-primary', 'btn-warning', 'btn-success', 'btn-primary']
					%>
          <div class="container-fluid nav-collapse">
            <ul class="nav-collapse collapse">
							<% PostGroup.all.each do |pg| %> 
								<% if PostCategory.where(:post_group_id=> pg.id).exists? %>
									<div class="btn-group">
										<button class="btn <%= arr[pg.id] %> dropdown-toggle" data-toggle="dropdown" >
											<%= pg.name %><span class="caret"></span>
										</button>
										<ul class="dropdown-menu">
											<% PostCategory.where(:post_group_id => pg.id).order("id asc").each do |c| %>
												<li><%= link_to "#{c.name}(#{c.posts.size})", posts_path(:category => c.name)  %></li>
											<% end %>
										</ul>
									</div>
								<% end %>
							<% end %>

							<div class="btn-group">
								<button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
									Welcome<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><%= link_to '---', '/locations/1' %></li>
									<li><%= link_to '---', '/locations/5' %></li>
									<li><%= link_to 'Yako', 'http://yakoblog.herokuapp.com/' %></li>
									<li><%= link_to 'Mobile Moncl', 'http://moncl.herokuapp.com/' %></li>
									<li><%= link_to 'DanuA', 'http://danua.herokuapp.com/' %></li>
									<li><%= link_to 'DanuB', 'http://danub.herokuapp.com/' %></li>
								</ul>
							</div>
							<%# <% PostGroup.all.each do |pg| %> 
							<%# 	<% if PostCategory.where(:psort => pg.psort).exists? %>
							<%# 		<li class="dropdown">
							<%# 		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= pg.name %><b class="caret"></b>
							<%# 			</a>
							<%# 			<ul class="dropdown-menu">
							<%# 				<% PostCategory.where(:psort => pg.psort).each do |c| %>
							<%# 					<li><%= link_to c.name, posts_path(:category => c.name)  %></li>
							<%# 				<% end %>
							<%# 			</ul>
							<%# 		</li>
							<%# 	<% end %>
							<%# <% end %>

								<% if user_signed_in? %>
										<%= link_to "#{current_user.email}", edit_user_registration_path %>
										<%= link_to "Logout", destroy_user_session_path, method: :delete %>
								<% else %>
										<%= link_to "Sign up", new_user_registration_path %>
										<%= link_to "Login", new_user_session_path %>
								<% end %>

								<%= form_tag posts_path, method: :get, :class => 'navbar-form pull-right' do %>
									<table align="right" class="search_table" cellspacing="0">
									  <tr>
											<td><%= text_field_tag :search, params[:search] %></td>
											<td><%= button_tag "Search", :class => "btn btn-success btn-mini" %></td>
									  </tr>
									</table>
								<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
			
				<div class="span2">
          <div class="well">
            <ul class="tree">
							<h5>카테고리</h5>
              <% PostGroup.all.each do |g| %>
							<li>
								<label class="tree-toggler", role="branch", data-toggle="branch" data-value="Bootstrap_Tree" ><%= g.name %></label>
								<ul class="branch in">
									<% PostCategory.where(:post_group_id => g.id).order("id asc").each do |c| %>
										<li><%= link_to "#{c.name}(#{c.posts.size})", posts_path(:category => c.name), :role => "leaf"  %></li>
									<% end %>
								</ul>
              </li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->				

        <div class="span10">
          <%= yield %>
        </div>
      </div><!--/row-->

			<div class="footer">
				<footer>
					<p>&copy; Noah's Company 2013. 여름배짱이. </p>
				</footer>
			</div>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>	
	<% if params[:category] == 'Result' %>
		<%= f.association :post_category, :prompt => "Category를 선택해 주세요." %>
	<% else %>
		<div class="control-group">
			<div class="controls">
				<h5 class="string"><%= @category.name %></h5>
			</div>
		</div>
		<%= f.input :post_category_id, :input_html => { :value => @category.id}, :as => :hidden %>
	<% end %>
	<%= f.input :user_id, :input_html => { :value => current_user.id}, :as => :hidden %>
	<%= f.input :title, :input_html => { :placeholder => "제목을 적어 주세요", :class=> 'span12'} %>
	<%= f.input :desc, :input_html => { :placeholder => "내용을 적어 주세요", :class=> 'span12 summernote'} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h3><%=t '.title', :default => @category %></h3>
</div>
<div align="right">Total Article : <%= @total_count %></div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>No</th>
      <th>제목</th>
      <th>작성자</th>
      <th>작성일</th>
      <th>조회수</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
		<% 
			i = 0
			if @page == 0 || @page == nil
				p = 1
			else
				p = @page
			end
			@posts.each do |post| 
				no = @total_count - ((p.to_i - 1) * @offset) - i 
				i += 1
		%>
      <tr>
				<td><%= no %></td>
				<td>
					<%= link_to post.title, post_path(post, :page => @page) %>
					<% if post.comments.exists? %>
						<small>(<%= post.comments.count %>)</small>
					<% end %>
				</td>
        <td><%= post.user.email.split('@')[0] %></td>
				<td><%= post.created_at.strftime('%Y.%m.%d') %></td>
				<td><%= post.impressionist_count(:filter=>:session_hash) %></td>
				<td>
				<% if user_signed_in? && post.user.id == current_user.id %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post, :page => @page, :category => @category), :class => 'btn btn-warning btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post, :page => @page, :category => @category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
											:class => 'btn btn-mini btn-danger' %>
				<% else %>
					<%= image_tag("/assets/images/ahsan/photo.jpg", :size => "16x16") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<%= image_tag("/assets/images/ahsan/photo.jpg", :size => "16x16") %>
				<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts, :theme => 'twitter-bootstrap' %>

<%= link_to t('.new', :default => t("helpers.links.new")), new_post_path(:category => @category),
            :class => 'btn btn-primary' %>
<%= link_to 'Home', root_path, :class => 'btn btn-inverse' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => @post.post_category.name  %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Avatar:</strong></dt>
  <dd><%= image_tag avatar_url(@post.user) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:post_category_id) %>:</strong></dt>
  <dd><%= @post.post_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @post.user.email.split('@')[0] %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong>Count:</strong></dt>
	<dd><%= @post.impressionist_count(:filter=>:session_hash) %></dd>
</dl>
<div class="content">
	<dd><%= raw @post.desc %></dd>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
		posts_path(:page => @page, :category => @post.post_category.name), :class => 'btn btn-success'  %>
<% if user_signed_in? && current_user.id == @post.user_id %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
		edit_post_path(@post, :category => @post.post_category.name), :class => 'btn btn-warning' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		post_path(@post, :category => @post.post_category.name, :page => @page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
							:class => 'btn btn-danger' %>
<% end %>							
</div>

<% if user_signed_in? %>
	<h5>댓글쓰기</h5>
	<%= render 'comments/form', :comment => Comment.new %><br/>
<% end %>

<%= render 'comments/index', :comments => @post.comments %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>